### ISSUE TITLE
[idea] Adding a HttpRequest action

### ISSUE THREAD

**Issue by Rukhkh** [VollRahm/NotEnoughHotkeys#10]
# idea
I saw this repo  https://github.com/sebinside/HotkeylessAHK

"Functionality

The Hotkeyless AHK script launches a lightweight web server. It listens to the endpoint localhost:42800/send/* for http requests and redirects them to the HotkeylessAHK.ahk script. To be more precise, if you call localhost:42800/send/HelloWorld, the HelloWorld()-function inside the AHK-file is executed:

`HelloWorld() {
    MsgBox, Hello World
}`

Also, you can include your AHK-scripts and define custom functionality in a nice and clean way - without loosing too much performance. You can use your web browser, shortcuts or utility hardware like the Stream Deck, like this:" 

it would be awesome if NotEnoughHotkeys would curl the server so the scripts will run
Sorry for my bad english
and thank you for your awesome program

**Comment by VollRahm** [comment]
I know that tool and the creator of it, its a neat project.
Adding support for HttpRequest actions is planned and I might start working on it again soon.

**Comment by VollRahm** [comment]
@Nomad1414 I implemented your idea in https://github.com/VollRahm/NotEnoughHotkeys/commit/612735ff205a6d4719c7e863ad85a9c3766a4c92, you can get the newest release [here](https://github.com/VollRahm/NotEnoughHotkeys/releases/latest)
