### ISSUE TITLE
[BUG] Second Keyboard Inputs are not Blocked

### ISSUE THREAD

**Issue by voltuz** [VollRahm/NotEnoughHotkeys#13]
When using my second keyboard (entirely for macros) it sends the right macro but it also sends the raw input/keystroke that i pressed

**Comment by VollRahm** [comment]
In every window or only in certain areas?

**Comment by voltuz** [comment]
Nope,
For example, in the windows search it sends both the macro and raw input. In the google search bar it sends only the macro
https://user-images.githubusercontent.com/68356371/127987147-26ee4d94-9f64-4af0-8344-734cb4ea7b66.mp4

**Comment by VollRahm** [comment]
Check the known issues in readme.md

**Comment by voltuz** [comment]
Oh yeah sorry i didn't saw it, thanks!

**Comment by VollRahm** [comment]
The reason this happens is, that NEH requires to place a hook using SetWindowsHookEx, and its not allowed to Block input in explorer.exe or Anti-cheat protected processes.
Im closing this now :D

**Comment by voltuz** [comment]
Sure thanks man!
