### ISSUE TITLE
[BUG] Can't delete

### ISSUE THREAD

**Issue by MelanX** [VollRahm/NotEnoughHotkeys#2]
I select a macro, I click the trashcan -> nothing happens

**Expected behavior**
Macro will be deleted

**Elevation of Process:**
Was it running as Administrator? yes

**Comment by VollRahm** [comment]
Fixed in https://github.com/VollRahm/NotEnoughHotkeys/commit/cb4b173986686c46838a87c3f4c24c8f01b9735c, closing
