### ISSUE TITLE
[BUG] Doesn't start properly from Windows Search

### ISSUE THREAD

**Issue by derkalaender** [VollRahm/NotEnoughHotkeys#6]
**Describe the bug**
Trying to start the exe from Windows Search results in a file not found error. Specifically "bin/NEHSubprocess.exe" cannot be found.

**To Reproduce**
1. Open up windows search (taskbar)
2. Search for 'NotEnoughHotkeys.exe'
3. Execute

**Expected behavior**
I expect it to load everything correctly. Or at least I would have expected it to also not work when called from a different directory from the cmd. But that works strangely enough. So this seems to really only be an issue with Windows Search

**Screenshots**
[Error Screenshot](https://cdn.discordapp.com/attachments/249666352787357696/697205074606161920/unknown.png)

**Elevation of Process:**
Was it running as Administrator? Nope

**Additional context**
-/-

**Comment by VollRahm** [comment]
Fixed in https://github.com/VollRahm/NotEnoughHotkeys/commit/b67775a8dcfa18d675e785a903ef5d20f7d814f4, closing
