### ISSUE TITLE
[BUG] Original letter is printed in Action

### ISSUE THREAD

**Issue by johanneslosch** [VollRahm/NotEnoughHotkeys#8]
**Describe the bug**
If you use the Action "Send Keystrokes" is the original letter visible

**To Reproduce**
Setup a Send Keystrokes hotkey and use it in a txt file (or discord/whatsapp)

**Expected behavior**
I expected that this letter would not appear

**Screenshots**
Exapmle:
![example image](https://user-images.githubusercontent.com/15651065/78781601-dac08600-79a0-11ea-8e40-8c4f2e69e0e6.png)
Macro:
![macro](https://user-images.githubusercontent.com/15651065/78781661-f330a080-79a0-11ea-9dde-52b84ca219a3.png)

**Elevation of Process:**
It is running as Administrator.

**Comment by VollRahm** [comment]
Does this persist when unchecking and rechecking the Enabled checkbox?

**Comment by johanneslosch** [comment]
No, thanks thats was the solution

**Comment by VollRahm** [comment]
Ok, this was the bug in #7 fixed in https://github.com/VollRahm/NotEnoughHotkeys/commit/b67775a8dcfa18d675e785a903ef5d20f7d814f4
