### ISSUE TITLE
[Enhancement] Keycode -> Key name when edit

### ISSUE THREAD

**Issue by MelanX** [VollRahm/NotEnoughHotkeys#9]
![image](https://user-images.githubusercontent.com/26039509/81501476-ddccd000-92d8-11ea-9800-85423f4335a9.png)
You lazy boy :)

**Comment by VollRahm** [comment]
Implemented in https://github.com/VollRahm/NotEnoughHotkeys/commit/e4af7ad8e047a3a455bcf32d50b90207008e5554
